server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-app
          __path__: /var/log/*.log
    pipeline_stages:
      - drop:
          expression: '.*\[GIN-debug\].*'
      - json:
          expressions:
            level: level
            msg: msg
            app: app_name
      - labels:
          level: level
          app: app