# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Show all available commands
    cmds:
      - echo "Available commands:"
      - task --list-all
    silent: true
  clean:
    desc: Clean up the project
    cmds:
      - go mod tidy
      - go fmt ./...
      - goimports -w .
  dev:
    cmds:
      - air
  setup:
    cmds:
      - go mod tidy
      - docker compose up -d
    silent: true
  test:
    desc: Run tests and linting with golangci-lint
    cmds:
      - go test ./...
      - golangci-lint run
    silent: true
