name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"
    - name: Unit Tests
      run: go test ./...
    - name: Linting
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        args: --timeout=5m

