name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: "1.25"
    - name: Unit Tests
      run: go test ./...
    - name: Linting
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m

