name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"
    - name: Unit Tests
      run: go test ./...
    - name: Linting
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        args: --timeout=5m

  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: test
    environment: main
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ncostamagna
        password: ${{ secrets.PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.app
        push: true
        tags: ncostamagna/passit-back:${{ github.sha }}
